# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 560)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #FFFAFA;\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 100, 471, 321))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 440, 84, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 440, 84, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 500, 211, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 20, 22, 21))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */    \n"
"    border-radius: 10px; /* задайте радиус, чтобы сделать кнопку круглой */\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    background-color: #F0F8FF; /* цвет кнопки */\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #DCDCDC;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 20, 22, 21))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */    \n"
"    border-radius: 10px; /* задайте радиус, чтобы сделать кнопку круглой */\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    background-color: #F0F8FF; /* цвет кнопки */\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #DCDCDC;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 55, 131, 23))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"       background-color: transparent;\n"
"       border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    font-family: Arial;\n"
"    font-size: 13px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Next"))
        self.pushButton_3.setText(_translate("MainWindow", "Photo"))
        self.pushButton_4.setText(_translate("MainWindow", "—"))
        self.pushButton_5.setText(_translate("MainWindow", "X"))
        self.pushButton_6.setText(_translate("MainWindow", "< Вернуться назад"))
