# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(390, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(388, 500))
        MainWindow.setMaximumSize(QtCore.QSize(390, 500))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #FFFAFA;\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(95, 395, 200, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(84, 40))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: #E0FFFF;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: #E0FFFF;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(95, 340, 200, 40))
        self.pushButton_2.setMinimumSize(QtCore.QSize(84, 40))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: #E0FFFF;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: #E0FFFF;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(60, 70, 271, 61))
        self.label.setStyleSheet("QLabel{\n"
"    font-family: Arial;\n"
"    font-size: 25px;\n"
"\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: none;  \n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(115, 150, 160, 160))
        self.label_2.setStyleSheet("QLabel{\n"
"    border: None\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("sign/pngwing.com.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 20, 22, 21))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */    \n"
"    border-radius: 10px; /* задайте радиус, чтобы сделать кнопку круглой */\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    background-color: #F0F8FF; /* цвет кнопки */\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #DCDCDC;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 20, 22, 21))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */    \n"
"    border-radius: 10px; /* задайте радиус, чтобы сделать кнопку круглой */\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 10px;\n"
"    background-color: #F0F8FF; /* цвет кнопки */\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #DCDCDC;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 140, 291, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D3D3D3;;\n"
"    border-radius: 10px; /* Задайте радиус, чтобы сделать форму овальной */\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    qproperty-alignment: \'AlignCenter\'; /* выравнивание по центру */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 311, 131))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"}")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(95, 395, 200, 41))
        self.pushButton_6.setMinimumSize(QtCore.QSize(84, 41))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 60, 131, 23))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"       background-color: transparent;\n"
"       border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    font-family: Arial;\n"
"    font-size: 13px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 170, 291, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D3D3D3;;\n"
"    border-radius: 10px; /* Задайте радиус, чтобы сделать форму овальной */\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    qproperty-alignment: \'AlignCenter\'; /* выравнивание по центру */\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 60, 131, 23))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"       background-color: transparent;\n"
"       border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    font-family: Arial;\n"
"    font-size: 13px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 250, 291, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D3D3D3;;\n"
"    border-radius: 10px; /* Задайте радиус, чтобы сделать форму овальной */\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    qproperty-alignment: \'AlignCenter\'; /* выравнивание по центру */\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 201, 16))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"\n"
"}")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 201, 16))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"\n"
"}")
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QtCore.QRect(95, 395, 200, 41))
        self.pushButton_8.setMinimumSize(QtCore.QSize(84, 41))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(105, 330, 181, 16))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"    \n"
"}")
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(230, 220, 101, 16))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"       background-color: transparent;\n"
"       border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: None;\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(95, 425, 200, 41))
        self.pushButton_10.setMinimumSize(QtCore.QSize(84, 41))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border: 2px solid #D3D3D3; /* цвет обводки */\n"
"    border-radius: 20px;\n"
"    background-color: #FFFAFA; /* цвет кнопки */\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #00CED1;\n"
"    border-radius: 12px;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #FFFAFA; /* цветтекста кнопки */\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #48D1CC;\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 220, 311, 181))
        self.label_7.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"}")
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 60, 131, 23))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    min-width: 80px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"       background-color: transparent;\n"
"       border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    font-family: Arial;\n"
"    font-size: 13px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080; /* цветтекста кнопки */\n"
"    text-decoration: underline;\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(130, 290, 141, 31))
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 110, 201, 16))
        self.label_8.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"\n"
"}")
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 140, 291, 31))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D3D3D3;;\n"
"    border-radius: 10px; /* Задайте радиус, чтобы сделать форму овальной */\n"
"    font-family: Arial;\n"
"    font-size: 16px;\n"
"\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    qproperty-alignment: \'AlignCenter\'; /* выравнивание по центру */\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(75, 180, 241, 16))
        self.label_9.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    font-weight: normal; /* жирный или обычный */\n"
"    color: #808080;\n"
"    border: None;\n"
"    \n"
"}")
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

         # email
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setVisible(False)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setVisible(False)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setVisible(False)
        self.label_3.setEnabled(False)
        self.label_3.setVisible(False)
        # logpass
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setVisible(False)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setVisible(False)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setVisible(False)
        self.label_4.setEnabled(False)
        self.label_4.setVisible(False)
        self.label_5.setEnabled(False)
        self.label_5.setVisible(False)
        self.label_6.setEnabled(False)
        self.label_6.setVisible(False)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setVisible(False)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setVisible(False)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setVisible(False)
        self.checkBox.setVisible(False)
        self.checkBox.setEnabled(False)
        # recovery
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setVisible(False)
        self.label_7.setEnabled(False)
        self.label_7.setVisible(False)
        self.label_8.setEnabled(False)
        self.label_8.setVisible(False)
        self.label_9.setEnabled(False)
        self.label_9.setVisible(False)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setVisible(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setVisible(False)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Managerio"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))
        self.pushButton_2.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label.setText(_translate("MainWindow", "Добро пожаловать в Managerio"))
        self.pushButton_3.setText(_translate("MainWindow", "X"))
        self.pushButton_4.setText(_translate("MainWindow", "—"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Для подтверждения вашей учетной записи, введите ваш действующий адрес электронной почты. Мы отправим вам уведомление и инструкции по завершению регистрации. Ваши личные данные будут храниться в безопасности и использоваться только в соответствии с политикой конфиденциальности.</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Отправить письмо"))
        self.pushButton_5.setText(_translate("MainWindow", "< Вернуться назад"))
        self.pushButton_7.setText(_translate("MainWindow", "< Вернуться назад"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Логин:</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Пароль:</p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Вход"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "Забыли пароль"))
        self.pushButton_10.setText(_translate("MainWindow", "Восстановить пароль"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Забыли пароль? Не переживайте! Мы поможем вам восстановить доступ к вашей учетной записи. Пожалуйста, введите адрес электронной почты, связанный с вашим аккаунтом, чтобы мы могли проверить ваш запрос.</p><p align=\"justify\">После верификации вашего адреса электронной почты, вам будет предоставлено поле для ввода секретного кода, который был выдан при регистрации вашего аккаунта. Пожалуйста, введите этот код для подтверждения вашей личности и продолжения процесса восстановления пароля.</p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "< Вернуться назад"))
        self.checkBox.setText(_translate("MainWindow", "Показывать пароль"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Логин:</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
